const { chromium }=require('playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
const fixture=JSON.parse(fs.readFileSync('E:/kanban-release/halloween-ranking-data.json','utf8'));
function expected(rows,period){const map=new Map();for(const r of rows){const p=period==='all'?r.allStageSales:r.salesPeriods?.[period];if(!p||p.actual===null||p.previous===null)continue;const v=map.get(r.spu)||{spu:r.spu,current:0,previous:0};v.current+=p.actual;v.previous+=p.previous;map.set(r.spu,v);}const all=[...map.values()].filter(x=>x.previous>0).map(x=>({...x,delta:x.current-x.previous}));return[all.filter(x=>x.delta>0).sort((a,b)=>b.delta-a.delta||a.spu.localeCompare(b.spu)).slice(0,10),all.filter(x=>x.delta<0).sort((a,b)=>a.delta-b.delta||a.spu.localeCompare(b.spu)).slice(0,10)];}
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const checks=[];try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));let data;
await page.route('**/qa-data',route=>route.fulfill({json:data}));
async function verify(rows,period){for(let i=0;i<2;i++){const actual=await page.locator('.ranking-list').nth(i).locator('tbody > tr:not(.rank-detail)').evaluateAll(trs=>trs.map(tr=>({spu:tr.querySelector('.rank-product span:last-child').textContent.trim(),current:Number(tr.children[1].textContent.replaceAll(',','').trim()),previous:Number(tr.children[2].textContent.replaceAll(',','').trim()),delta:Number(tr.querySelector('.rank-delta').textContent.replaceAll(',','').trim())})));assert.deepEqual(actual,expected(rows,period)[i]);}}
for(const [name,owners,defaults] of [['manager',['梁泽才'],null],['operator',['吴婷'],['吴婷']],['leader',['陈宇星','唐宇璐','周小涵','谢玉燕'],['陈宇星','唐宇璐','周小涵','谢玉燕']],['super',null,null]]){
const allowed=fixture.rows.filter(r=>owners===null||owners.includes(r.owner)).map(r=>({...r,id:owners===null?r.id:'ranking|'+r.id+'|'+r.owner,canConfirm:false}));data={...fixture,rankingRows:allowed,viewer:{defaultResponsibles:defaults,defaultLabel:defaults?'本人／团队':'全部负责人'}};
await page.goto('http://127.0.0.1:8772/preview.html');await page.locator('.ranking-title').click();await verify(allowed,'all');await page.getByLabel('负责人',{exact:true}).selectOption('');await verify(allowed,'all');checks.push(name+': all-owner filter cannot widen backend cohort');await page.getByRole('button',{name:'所选阶段',exact:true}).click();await page.locator('.stage-select').filter({hasText:'检查与预估'}).click();await verify(allowed,3);checks.push(name+': selected-stage matches authorized cohort');
if(name==='manager'){await page.getByRole('button',{name:'全阶段',exact:true}).click();await page.locator('.rank-product').first().click();await page.locator('.rank-site .link').first().click();await page.locator('.ant-modal').waitFor();assert.ok((await page.locator('.ant-modal').innerText()).includes('梁泽才'));await page.locator('.ant-modal-close').click();checks.push('manager ranking detail resolves its authorized row');await page.screenshot({path:__dirname+'/manager.png',fullPage:true});}}
data=JSON.parse(fs.readFileSync('E:/kanban-release/halloween-ranking-ownership-20260929/liang-preview.json','utf8'));await page.reload();await page.locator('.ranking-title').click();await verify(data.rankingRows,'all');checks.push('actual manager API payload: only owned SPU/shop units reach both rankings');await page.getByLabel('负责人',{exact:true}).selectOption('王妍琪');assert.equal(await page.locator('.rank-product').count(),0);await page.getByLabel('负责人',{exact:true}).selectOption('');await verify(data.rankingRows,'all');checks.push('actual manager cannot rank a colleague via filter');
data={...fixture};delete data.rankingRows;await page.reload();await page.locator('.ranking-title').click();assert.equal(await page.locator('.rank-product').count(),0);checks.push('missing ranking payload fails closed, never falls back to all rows');assert.deepEqual(errors,[]);fs.writeFileSync(__dirname+'/verification.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,errors}));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
