const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const fixture=JSON.parse(fs.readFileSync('E:/kanban-release/halloween-ranking-data.json','utf8'));
const checks=[];
function oracle(rows,period=null){const map=new Map();for(const r of rows){const p=period===null?r.allStageSales:r.salesPeriods?.[period];if(!p||p.actual===null||p.previous===null)continue;const x=map.get(r.spu)||{spu:r.spu,current:0,previous:0};x.current+=p.actual;x.previous+=p.previous;map.set(r.spu,x);}const all=[...map.values()].filter(p=>p.previous>0).map(p=>({...p,delta:p.current-p.previous}));return [all.filter(p=>p.delta>0).sort((a,b)=>b.delta-a.delta||a.spu.localeCompare(b.spu)).slice(0,10),all.filter(p=>p.delta<0).sort((a,b)=>a.delta-b.delta||a.spu.localeCompare(b.spu)).slice(0,10)];}
async function verifyLists(page,rows,period=null){const expected=oracle(rows,period);if(!await page.locator(".year-ranking").evaluate(e=>e.open))await page.locator(".ranking-title").click();for(let i=0;i<2;i++){const list=page.locator('.ranking-list').nth(i);const actual=await list.locator('tbody > tr:not(.rank-detail)').evaluateAll(trs=>trs.map(tr=>({spu:tr.querySelector('.rank-product span:last-child').textContent.trim(),current:Number(tr.children[1].textContent.replaceAll(',','').trim()),previous:Number(tr.children[2].textContent.replaceAll(',','').trim()),delta:Number(tr.querySelector('.rank-delta').textContent.replaceAll(',','').trim())})));assert.deepEqual(actual,expected[i]);}checks.push('Ranking matches independent full-window aggregation');}
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8772/preview.html');await page.locator('.year-ranking').waitFor();assert.equal(await page.locator('.year-ranking[open]').count(),0);assert.equal(await page.getByText('哪些产品带动了同比',{exact:true}).count(),0);assert.equal(await page.getByRole('group',{name:'同比排名周期'}).isVisible(),false);checks.push('One disclosure default collapsed; only requested period toggle inside');await page.screenshot({path:path.join(__dirname,'desktop.png'),fullPage:true});await page.locator('.year-ranking').screenshot({path:path.join(__dirname,'desktop-collapsed.png')});await verifyLists(page,fixture.rows);await page.locator('.year-ranking').screenshot({path:path.join(__dirname,'desktop-expanded.png')});
const before=await page.locator('.year-ranking').innerText();await page.locator('.stage-select').filter({hasText:'增加有效广告'}).click();assert.equal(await page.locator('.year-ranking').innerText(),before);checks.push('All-stage rankings independent of selected timeline phase');await page.getByRole('button',{name:'所选阶段',exact:true}).click();assert.equal(await page.locator('.rank-product').count(),0);await page.locator('.stage-select').filter({hasText:'检查与预估'}).click();await verifyLists(page,fixture.rows,3);await page.getByRole('button',{name:'全阶段',exact:true}).click();await verifyLists(page,fixture.rows);checks.push('Selected stage/all-stage switch both rankings together');
await page.getByLabel('站点',{exact:true}).selectOption('CA');await verifyLists(page,fixture.rows.filter(r=>r.site==='CA'));checks.push('Site filtering recomputes rankings');await page.getByLabel('站点',{exact:true}).selectOption('');await page.getByLabel('部门',{exact:true}).selectOption('亚马逊二部');await verifyLists(page,fixture.rows.filter(r=>r.department==='亚马逊二部'));checks.push('Department filtering recomputes rankings');await page.getByLabel('部门',{exact:true}).selectOption('');await verifyLists(page,fixture.rows);
await page.locator('.rank-product').first().click();await page.locator('.rank-site .link').first().click();await page.locator('.ant-modal').waitFor();assert.ok(await page.locator('.ant-modal').isVisible());await page.locator('.ant-modal-close').click();checks.push('SPU expands sites and opens existing product detail');
await page.locator('.ranking-title').click();await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(__dirname,'mobile.png'),fullPage:true});await page.locator('.year-ranking').screenshot({path:path.join(__dirname,'mobile-collapsed.png')});await verifyLists(page,fixture.rows);await page.locator('.year-ranking').screenshot({path:path.join(__dirname,'mobile-expanded.png')});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks.push('390px mobile no document horizontal overflow');
const summary=page.locator('.ranking-title').first();await summary.focus();await page.keyboard.press('Enter');assert.equal(await page.locator('.year-ranking').evaluate(e=>e.open),false);checks.push('Keyboard disclosure works');
await page.route('**/qa-data',route=>route.fulfill({json:{...fixture,rows:[]}}));await page.reload();await page.locator('.ranking-title').first().click();assert.ok(await page.getByText('暂无可比销量',{exact:true}).first().isVisible());checks.push('Empty cohort has no invented zero rankings');assert.deepEqual(errors,[]);checks.push('No browser runtime errors');fs.writeFileSync(path.join(__dirname,'verification.json'),JSON.stringify({checks,errors,source:'readonly production data snapshot',rows:fixture.rows.length,top:oracle(fixture.rows).map(list=>list.slice(0,3))},null,2));console.log(JSON.stringify({passed:checks.length,top:oracle(fixture.rows).map(list=>list.slice(0,3))}));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
